### ISSUE TITLE
Hardware Schematic and howto

### ISSUE THREAD

**Issue by rabimba** [jpoles1/dak#1]
Hi,

Just wanted to know if you have plan to publish how to actually string up and build the hardware. What sensors you all used and in which configuration. That will help anyone who likes to fork the project maybe and play with it!

**Comment by jpoles1** [comment]
Hi @rabimba, sorry it took so long to respond. We hope to post a detailed and clean (non-handwritten) schematic of the board very soon!

**Comment by jpoles1** [comment]
@rabimba I've drawn up a diagram of our breadboard. It can be found here:
https://github.com/jpoles1/dak/tree/master/hardware

**Comment by rabimba** [comment]
Perfect! And thanks.
Now if you just had a list of components you used (and what you have in mind to make it more powerful), then other might jump in onboard to replicate this and contribute!

**Comment by jpoles1** [comment]
Added a BOM (part list) to the above page. I will work on writing up some possible ideas for extensions to the project!

**Comment by jpoles1** [comment]
I'll be adding ideas for improvements to the issues tracker as I come up with em.
